
debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost/app_db
    username: postgres
    password: qwerty
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  server:
    port: 8080
  hostname: 127.0.0.1:${server.port}