
debug: false


spring:
  r2dbc: 
    url: ${R2DBC_DB_URL:r2dbc:postgresql://localhost:5432/app_db}
    username: postgres
    password: qwerty
  flyway: 
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}

