INSERT INTO "bot" (id, name, avatar_filename, category_id)
VALUES
(DEFAULT, 'Jorik', 'robot1.jpeg', (SELECT id FROM "bot_category" WHERE name='Media' LIMIT 1)),
(DEFAULT, 'Rick', 'robot2.jpeg', (SELECT id FROM "bot_category" WHERE name='Blogs' LIMIT 1)),
(DEFAULT, 'Vasya', 'robot3.jpeg', (SELECT id FROM "bot_category" WHERE name='Education' LIMIT 1)),
(DEFAULT, 'Mitya', 'robot4.jpeg', (SELECT id FROM "bot_category" WHERE name='Health' LIMIT 1)),
(DEFAULT, 'Rex', 'robot5.jpeg', (SELECT id FROM "bot_category" WHERE name='Music' LIMIT 1)),
(DEFAULT, 'Max', 'robot1.jpeg', (SELECT id FROM "bot_category" WHERE name='News' LIMIT 1)),
(DEFAULT, 'Sanyok', 'robot2.jpeg', (SELECT id FROM "bot_category" WHERE name='Animals' LIMIT 1)),
(DEFAULT, 'Alex', 'robot3.jpeg', (SELECT id FROM "bot_category" WHERE name='Fashion' LIMIT 1)),
(DEFAULT, 'Bobby', 'robot4.jpeg', (SELECT id FROM "bot_category" WHERE name='Media' LIMIT 1)),
(DEFAULT, 'Jonny', 'robot5.jpeg', (SELECT id FROM "bot_category" WHERE name='Blogs' LIMIT 1)),
(DEFAULT, 'Pupsik', 'robot1.jpeg', (SELECT id FROM "bot_category" WHERE name='Education' LIMIT 1)),
(DEFAULT, 'Linus', 'robot2.jpeg', (SELECT id FROM "bot_category" WHERE name='Health' LIMIT 1)),
(DEFAULT, 'Bill', 'robot3.jpeg', (SELECT id FROM "bot_category" WHERE name='Music' LIMIT 1)),
(DEFAULT, 'Musk', 'robot4.jpeg', (SELECT id FROM "bot_category" WHERE name='News' LIMIT 1)),
(DEFAULT, 'Dodon', 'robot5.jpeg', (SELECT id FROM "bot_category" WHERE name='Animals' LIMIT 1)),
(DEFAULT, 'John', 'robot1.jpeg', (SELECT id FROM "bot_category" WHERE name='Fashion' LIMIT 1)),
(DEFAULT, 'Martin', 'robot2.jpeg', (SELECT id FROM "bot_category" WHERE name='Media' LIMIT 1)),
(DEFAULT, 'Marusya', 'robot3.jpeg', (SELECT id FROM "bot_category" WHERE name='Blogs' LIMIT 1)),
(DEFAULT, 'Irina', 'robot4.jpeg', (SELECT id FROM "bot_category" WHERE name='Education' LIMIT 1)),
(DEFAULT, 'Marina', 'robot5.jpeg', (SELECT id FROM "bot_category" WHERE name='Health' LIMIT 1)),
(DEFAULT, 'Zozik', 'robot1.jpeg', (SELECT id FROM "bot_category" WHERE name='Music' LIMIT 1)),
(DEFAULT, 'Julik', 'robot2.jpeg', (SELECT id FROM "bot_category" WHERE name='News' LIMIT 1)),
(DEFAULT, 'Frosya', 'robot3.jpeg', (SELECT id FROM "bot_category" WHERE name='Animals' LIMIT 1)),
(DEFAULT, 'Dimon', NULL, (SELECT id FROM "bot_category" WHERE name='Fashion' LIMIT 1)),
(DEFAULT, 'Vlad', NULL, NULL),
(DEFAULT, 'Eskobar', NULL, NULL);

